Zielsystem Userpasswort:
##############################################################################
export PT = 'spitzenPasswort'
##############################################################################

# Pfad zu den Openhab-Installationsdateien:
#
# - distribution-$(OPENHABVERSION)-runtime.zip
# -                               -addons.zip
# - org.openhab.io.myopenhab-$(OPENHABVERSION).jar
# - jdk-8u33-linux-arm-vfp-hflt.tar.gz 
##############################################################################
export OPENHABDOWNLOADS = /home/...
##############################################################################


# IP-Adresse C1612-Server:
##############################################################################
export C1612ServerIP = 192.168.6.66
##############################################################################
