#!/bin/bash

if [ "$#" != 2 ]; then
	echo "Aufruf: $0 <file> <address>"
	exit 1
fi

echo "Pruefe Backup Datei $1..."
if [ -f $1 ]; then
	if grep -q '^# HCAN Backup File v1' $1; then
		echo "... ok."
		echo
		echo "Beim Zurueckspielen der Backup Config auf das Board"
		echo "werden ALLE Konfigurationsdaten ueberschrieben."
		echo "Soll das Backup WIRKLICH eingespielt werden ?"
		echo 
		echo "(j/N) ?"
		read i
		case $i in 
			j)
				echo "Konfiguration wird uebertragen..."
				telican -c $2 -r $1 -e ''
				echo "... fertig. Bitte Konfiguration manuell pruefen"
				echo "und neu laden ('reload')."
				exit 0
			;;
			*)
				echo
				echo "Abbruch gewuenscht..."
				exit 1
			;;
		esac
		
		echo "fertig."
	else
		echo "Fehler: $1 ist keine korrekte Backup Datei."
	fi
else
	echo "Fehler: $1 existiert nicht oder ist nicht lesbar."
fi

