#!/bin/bash

if [ "$#" != 1 ]; then
	echo "Aufruf: $0 <address>"
	exit 1
fi

echo "Erstelle Backup der Konfiguration von Board $1..."

(
echo "######################################################"
echo "# HCAN Backup File v1"
echo "#"
echo "# Date: `date`"
echo "# User: $USER"
echo "# Addr: $1"
echo "#"
telican -c $1 -e "show system; show uptime" | awk '{ print "# "$0 }'
echo "#"
echo "######################################################"
echo
echo "# Format the EEROM to have a clean start..."
echo "Format"
echo
echo "# Config START"
telican -c $1 -e "show conf"
echo "# Config END"

) > backup-board-$1-`date +%Y%m%d`.cf

echo "... fertig."

